version: '3'
services:
  selenium:
    container_name: selenium-chrome
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
  python:
    container_name: python
    build: ./python
    volumes:
      - ./python/src:/opt/app
    tty: true
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - python
